author: lluisrojass@gmail.com
images:
  - id: b570525d8dfc
    takenTimestamp: 1622076483000
    importTimestamp: 1630967596247
    description: null
    location:
      lat: 40.660767
      lon: -73.978867
      timeZone: America/New_York
      readable: Prospect Park, Brooklyn, NY
  - id: c38784ffbbad
    takenTimestamp: 1622080869000
    importTimestamp: 1630968631850
    description: null
    location:
      lat: 40.706375
      lon: -73.99038
      timeZone: America/New_York
      readable: Manhattan Bridge, New York, New York
  - id: 74c0d9d9adf9
    takenTimestamp: 1624324006000
    importTimestamp: 1630968749009
    description: null
    location:
      lat: 40.640067
      lon: -73.967125
      timeZone: America/New_York
      readable: Cortelyou Road, Brooklyn, New York
  - id: cfa3c68203fb
    takenTimestamp: 1624482628000
    importTimestamp: 1630968874226
    description: null
    location:
      lat: 40.658553
      lon: -73.968383
      timeZone: America/New_York
      readable: Prospect Park, Brooklyn, New York
  - id: 3777ba216260
    takenTimestamp: 1624482651000
    importTimestamp: 1630968993974
    description: null
    location:
      lat: 40.658438
      lon: -73.9683
      timeZone: America/New_York
      readable: Prospect Park, Brooklyn, New York
  - id: 46ac75b298ee
    takenTimestamp: 1624638798000
    importTimestamp: 1630969210958
    description: null
    location:
      lat: 40.64042
      lon: -73.965242
      timeZone: America/New_York
      readable: Ditmas Park, Brooklyn, New York
  - id: "983597645e20"
    takenTimestamp: 1624730606000
    importTimestamp: 1630969309012
    description: null
    location:
      readable: Coney Island, Brooklyn, New York
  - id: 0052e1fe1616
    takenTimestamp: 1624922355000
    importTimestamp: 1630969443855
    description: null
    location:
      lat: 40.73562
      lon: -73.98993
      timeZone: America/New_York
      readable: Union Square Park, New York, New York
  - id: d8349e0fdb1d
    takenTimestamp: 1624922363000
    importTimestamp: 1630969615839
    description: null
    location:
      lat: 40.73563
      lon: -73.989913
      timeZone: America/New_York
      readable: Union Square Park, New York, New York
  - id: ab2b0a57470a
    takenTimestamp: 1625247230000
    importTimestamp: 1630970267603
    description: null
    location:
      lat: 40.5742
      lon: -73.973587
      timeZone: America/New_York
      readable: New York Aquarium, Brooklyn, New York
  - id: 9656212ea3f2
    takenTimestamp: 1625250606000
    importTimestamp: 1630970343561
    description: null
    location:
      lat: 40.574458
      lon: -73.973647
      timeZone: America/New_York
      readable: New York Aquarium, Brooklyn, New York
  - id: 8332e3dc3ffa
    takenTimestamp: 1626808318000
    importTimestamp: 1630970409789
    description: null
    location:
      lat: 44.528887
      lon: -73.46112
      timeZone: America/New_York
      readable: Ausable Chasm, New York
  - id: b17f5e5865cc
    takenTimestamp: 1628553251000
    importTimestamp: 1630970492380
    description: null
    location:
      lat: 40.660662
      lon: -73.965875
      timeZone: America/New_York
      readable: Prospect Park, Brooklyn, New York
  - id: 09e30ac459b5
    takenTimestamp: 1629680846000
    importTimestamp: 1630970551284
    description: null
    location:
      lat: 40.640187
      lon: -73.965508
      timeZone: America/New_York
      readable: Ditmas Park, Brooklyn, New York
  - id: f77b2837485c
    takenTimestamp: 1629690502000
    importTimestamp: 1630970606418
    description: null
    location:
      lat: 40.640187
      lon: -73.965592
      timeZone: America/New_York
      readable: Ditmas Park, Brooklyn, New York
  - id: 566221041bc3
    takenTimestamp: 1630169605000
    importTimestamp: 1630970693351
    description: null
    location:
      lat: 41.946637
      lon: -74.005822
      timeZone: America/New_York
      readable: Kingston, New York
  - id: 65048339d835
    takenTimestamp: 1630711260000
    importTimestamp: 1630970766251
    description: null
    location:
      lat: 40.644088
      lon: -73.966417
      timeZone: America/New_York
      readable: Ditmas Park, Brooklyn, New York
  - id: e587cedd4091
    takenTimestamp: 1631321852000
    importTimestamp: 1632585315960
    description: null
    location:
      lat: 40.756912
      lon: -73.846855
      timeZone: America/New_York
      readable: Citi Field, Queens, New York
  - id: b179f791d9aa
    takenTimestamp: 1631384957000
    importTimestamp: 1632585463198
    description: null
    location:
      lat: 40.56473
      lon: -73.877363
      timeZone: America/New_York
      readable: Fort Tilden, Queens, New York
  - id: 0a64dc849bb9
    takenTimestamp: 1631481289000
    importTimestamp: 1632585628006
    description: null
    location:
      lat: 40.735512
      lon: -73.990355
      timeZone: America/New_York
      readable: Union Square Park, New York, New York
  - id: 719a563bdf5e
    takenTimestamp: 1631487164000
    importTimestamp: 1632585738786
    description: me!
    location:
      lat: 40.640475
      lon: -73.965408
      timeZone: America/New_York
      readable: Ditmas Park, Brooklyn, New York
  - id: 6d822a6c354f
    takenTimestamp: 1631830624000
    importTimestamp: 1632585807599
    description: Brother Leo Obrien. Outstanding Student-Athlete Award. John Biscaino 1988.
    location:
      lat: 40.640788
      lon: -73.965163
      timeZone: America/New_York
      readable: Ditmas Park, Brooklyn, New York
  - id: 7d13cd65ae7f
    takenTimestamp: 1630171844000
    importTimestamp: 1632607855774
    description: null
    location:
      lat: 42.193337
      lon: -74.063308
      timeZone: America/New_York
      readable: Palenville, New York
  - id: 1ea5b4294298
    takenTimestamp: 1634696617000
    importTimestamp: 1636223305358
    description: ..Hogwash! ..Balderdash!
    location:
      altitude: 13.303371435169149
      lat: 40.731889
      lon: -73.989106
      timeZone: America/New_York
      readable: Webster Hall, Brooklyn, New York
  - id: f55ab4e31c48
    takenTimestamp: 1636256762000
    importTimestamp: 1636263998262
    description: null
    location:
      altitude: 45.59907153407892
      lat: 40.661106
      lon: -73.977678
      timeZone: America/New_York
      readable: Outer Loop, Prospect Park, Brooklyn, NY
  - id: b571b9f66a6d
    takenTimestamp: 1636746551000
    importTimestamp: 1637189333746
    description: null
    location:
      altitude: 21.811893505847227
      lat: 38.889317
      lon: -77.049811
      timeZone: America/New_York
      readable: Lincoln Memorial, Washington DC
  - id: 0c1ce66179c7
    takenTimestamp: 1636751682000
    importTimestamp: 1637189628208
    description: null
    location:
      altitude: 29.34814453125
      lat: 38.886967
      lon: -77.032219
      timeZone: America/New_York
      readable: United States Holocaust Memorial Museum, Washington DC
  - id: 023148fc1674
    takenTimestamp: 1636757671000
    importTimestamp: 1637189792770
    description: null
    location:
      altitude: 0.3024635312632407
      lat: 38.887781
      lon: -77.047439
      timeZone: America/New_York
      readable: Korean War Veterans Memorial, Washington DC
  - id: 1cc55121de33
    takenTimestamp: 1636757895000
    importTimestamp: 1637189889690
    description: null
    location:
      altitude: 12.50445937690898
      lat: 38.888508
      lon: -77.049058
      timeZone: America/New_York
      readable: Washington DC
